version: '3.5'

services:
    web-back-end:
        image: backend_example_dockerized
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis-service
    web-front-end:
        image: example-frontend-dockerized
        ports:
            - 5000:5000
    redis-service:
        image: redis:latest
        ports:
            - 6379:6379